require('settings')
require('miscelanious')
require('plugins')
require('treesitter')
require('keybinds')
require('nvim-cmp')
require('autocommands')
require('lsp')
require('nvim-dap')
-- require('toggleterm')
